import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";

const montserrat = Montserrat({ subsets: ["latin"], 

});

export const metadata: Metadata = {
  title: "Simmons Casa Orner | Produtos",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png', // /public path
  },
};

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
